server:
  port: 8080
  #设置响应为utf-8
  servlet:
    encoding:
      force-response: true
robot:
  #机器人token
  token: 1/xxxxxxxxx=/xxxxxxxx==
  #机器人encryptKey
  encryptKey: "xxxxxxxx"
  #机器人加密偏移量
  iv: 0012346521232145
  #机器人校验token
  veriftoken: xxxxxxxxxx
  #服务器列表 每一个服务器信息用 , 隔开 每个服务器内的信息用  - 隔开
  armaserver:
    特别行动-150.138.72.34-2303,逃离-150.138.72.34-4303,BRPVP-150.138.72.34-6667,战队服-150.138.72.34-7303
web-socketio:
  #机器人API地址
  host: "https://www.kaiheila.cn/api/v3/"

